# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountuser',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Одежда', 'Одежда'), ('Аксессуары', 'Аксессуары'), ('Техника', 'Техника'), ('Еда', 'Еда'), ('Услуги', 'Услуги')], max_length=36),
        ),
        migrations.AlterField(
            model_name='discountuser',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбрано', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('Одежда', 'Одежда'), ('Аксессуары', 'Аксессуары'), ('Техника', 'Техника'), ('Еда', 'Еда'), ('Услуги', 'Услуги')], default='Не выбрано', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
