# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_auto_20170520_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountuser',
            name='status',
            field=models.CharField(choices=[('сustomer', 'Покупатель'), ('stuff', 'Владелец магазина')], default='Не выбрано', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shop_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
