# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0003_auto_20170522_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='shop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
