# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбрано', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('categories', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Одежда', 'Одежда'), ('Аксессуары', 'Аксессуары'), ('Техника', 'Техника'), ('Еда', 'Еда'), ('Услуги', 'Услуги')], max_length=36, null=True)),
                ('status', models.CharField(choices=[('сustomer', 'Покупатель'), ('stuff', 'Владелец магазина')], default='Не выбрано', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DiscountUser',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('Одежда', 'Одежда'), ('Аксессуары', 'Аксессуары'), ('Техника', 'Техника'), ('Еда', 'Еда'), ('Услуги', 'Услуги')], default='Не выбрано', max_length=20)),
                ('seller_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposition', models.CharField(max_length=255)),
                ('terms', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('shop_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
    ]
